apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-to-loki
  namespace: discord-to-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-to-loki
  template:
    metadata:
      labels:
        app: discord-to-loki
    spec:
      containers:
        - name: discord-to-loki
          image: cr.jdbnet.co.uk/public/discord-to-loki:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: "discord-to-loki"
          env:
            - name: LOKI_URL
              value: "https://loki.example.com"
            - name: LOKI_USERNAME
              value: "your_username"
            - name: LOKI_PASSWORD
              value: "your_password"
---
apiVersion: v1
kind: Service
metadata:
  name: discord-to-loki-ingress-service
  namespace: discord-to-loki
spec:
  selector:
    app: discord-to-loki
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discord-to-loki-ingress
  namespace: discord-to-loki
spec:
  rules:
  - host: discord-to-loki.jdbnet.co.uk
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: discord-to-loki-ingress-service
            port:
              number: 80